@startuml node_binding/handle_wrap

!include async_wrap.puml

namespace lib {
  namespace handle_wrap <<InternalNodeModule>> {
    class HandleWrap extends lib.async_wrap.AsyncWrap {
      close()
      hasRef()
      ref()
      unref()
    }
  }
}

@enduml
