@startuml node_binding/stream_wrap

!include handle_wrap.puml
!include async_wrap.puml
!include stream_base.puml

namespace lib {
  namespace stream_wrap <<InternalNodeModule>> {
    class LibuvStreamWrap extends lib.handle_wrap.HandleWrap, lib.stream_base.StreamBase {
      +writeQueueSize: ReadOnly<number>
      setBlocking()
    }

    class ShutdownWrap extends lib.async_wrap.AsyncWrap {
      oncomplete
      callback
      handler
    }

    class WriteWrap extends lib.async_wrap.AsyncWrap {

    }

    enum CONSTANTS {
      kReadBytesOrError,
      kArrayBufferOffset,
      kBytesWritten,
      kLastWriteWasAsync
    }

    class LibGlobal {
      streamBaseState
    }
  }
}

@enduml
