@startuml async_wrap
namespace node {
  class AsyncWrap extends BaseObject {
    +AsyncWrap(Environment* env, v8::Local<v8::Object> object, ProviderType provider, double execution_async_id = kInvalidAsyncId)
  }

  enum ProviderType {
    PROVIDER_TCPWRAP
    PROVIDER_TCPSERVERWRAP
  }
}
@enduml
